### ISSUE TITLE
RStudio fails to launch - EXCEPT for projects with renv activated

### ISSUE THREAD

**Issue by orderlyquant** [rstudio/renv#1302]
A strange issue developed on my Mac last Friday. After a sequence of innocuous events (i.e. I don't remember exactly what I did, but didn't think I was doing anything potentially dangerous), RStudio started hanging on startup (and when changing projects), if the project was not controlled by `renv`.

I have gone through all of the following to troubleshoot:

[Understanding R Startup](https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/)
[RStudio Desktop IDE Will Not Start](https://support.posit.co/hc/en-us/articles/200488508-RStudio-Desktop-Will-Not-Start)
[Resetting RStudio Desktop's State](https://support.posit.co/hc/en-us/articles/200534577-Resetting-RStudio-s-State)

And have not been able to resolve.

## Where I currently stand

- I have no problem opening projects controlled by `renv`, i.e. have a 'renv.lock' file and 'renv' directory
- I can not open RStudio by double-clicking  on the RStudio icon
- I CAN open RStudio by executing the following at the command line: '/Applications/RStudio.app/Contents/MacOS/RStudio &'

## Details

RStudio: version 2022.12.0 build 353
R: version 4.2.2
MacOs: Ventura 13.2

I appreciate any help/thoughts.

-Brandon

**Comment by kevinushey** [comment]
To double-check, what are the contents of your `~/.Rprofile` and `~/.Renviron` files?

**Comment by orderlyquant** [comment]
`~/.Rprofile` is empty, `~/.Renviron` does not exist.

For further background, R.app launches with no issue.

**Comment by orderlyquant** [comment]
I've attached lightly edited diagnostics report.

I agree the behavior is mysterious and seems backwards to me. As I would expected problems with `renv` projects, not the other way around.

Btw, after running the diagnostics earlier today, I ran the command without `--run-diagnostics` and RStudio launches with no problems no matter what project was last active. It does however, include the following message

```
~ bfarr$ /Applications/RStudio.app/Contents/MacOS/RStudio
objc[26942]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x241a1d518) and /Applications/RStudio.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1059cd348). One of the two will be used. Which one is undefined.

```


[diagnostics-report.txt](https://github.com/rstudio/renv/files/11535791/diagnostics-report.txt)

**Comment by kevinushey** [comment]
> objc[26942]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x241a1d518) and /Applications/RStudio.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1059cd348). One of the two will be used. Which one is undefined.

I believe this can be ignored.

Unfortunately, nothing stands out from the diagnostics report. It might be worth trying out the [latest release](https://posit.co/download/rstudio-desktop/) of RStudio, or even a [daily build](https://dailies.rstudio.com/) in case the issue has been resolved in a newer RStudio release.

**Comment by orderlyquant** [comment]
I appreciate all of the help on this, but the latest release didn't resolve it either.

I'm surprised that there is differential behavior between double-clicking (either RStudio or an `.rproj` file) and doing effectively the same thing from the command line. For example, `project-a` which doesn't use `renv` won't launch when double-clicking on the `project-a.rproj` file. Yet, it will open when running `open project-a.rproj` from the project directory.

Is there something "executed" in the GUI implementation that is skipped when running via the command line?

**Comment by hadley** [comment]
Maybe try clearing out your system library (`.libPaths()[1])`? It's possible that you somehow corrupted a package that RStudio loads automatically. renv projects would use their own local copy, which would explain why they still succeed.

**Comment by orderlyquant** [comment]
Clearing out the system library didn't resolve the issue. Any thoughts on the differential steps taken when `open`ing a `.Rproj` file via the terminal versus double-clicking the `.Rproj` in the Finder? I'm glad to have found a way to keep working, but am interested in getting to the bottom of this. These events increase my knowledge of how everything works. Thanks again.

**Comment by hadley** [comment]
I'm not aware of any differences, sorry.

Unfortunately this sounds like it's outside of the scope of support we can provide for the renv package, so I'm going to close this issue.

**Comment by orderlyquant** [comment]
Understood, and again, thanks for the help.
