### ISSUE TITLE
The requested URL returned error: 404 

### ISSUE THREAD

**Issue by hugeme** [rstudio/renv#96]
Hello,

I just migrated from packrat to renv via `renv::migrate()` without any errors being thrown. However, I cant install any packages within the project anymore:

> renv::install("ggplot2")
Retrieving 'https://cran.rstudio.com/src/contrib/ggplot2_3.2.0.tgz' ...
curl: (22) The requested URL returned error: 404 
curl: (22) The requested URL returned error: 404 
* The lockfile is already up to date.

Packages is being retrieved from: `https://cran.rstudio.com/src/contrib/ggplot2_3.2.0.tgz`
rather than `https://cran.rstudio.com/src/contrib/ggplot2_3.2.0.tar.gz`

I guess I have to set `options(repos = c(CRAN = "http://cran.rstudio.com"))` to something else?

**Comment by kevinushey** [comment]
It looks like the wrong package URL is being constructed -- the suffix `.tgz` is being used, but the repository directory for source packages is being consulted instead.

Can you provide any other information? What is the output of `utils::sessionInfo()` and `getOption("pkgType")`?

**Comment by kevinushey** [comment]
The output of `getOption("repos")` could be helpful, as well.

**Comment by hugeme** [comment]
> sessionInfo()
    R version 3.6.0 (2019-04-26)
    Platform: x86_64-apple-darwin18.5.0 (64-bit)
    Running under: macOS Mojave 10.14.4

    Matrix products: default
    BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    LAPACK: /usr/local/Cellar/openblas/0.3.6_1/lib/libopenblasp-r0.3.6.dylib

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices datasets  utils     methods   base     

    loaded via a namespace (and not attached):
    [1] compiler_3.6.0 tools_3.6.0    packrat_0.5.0  renv_0.5.0-61 



> getOption("pkgType")
[1] "source"


> getOption("repos")
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE

**Comment by hugeme** [comment]
[renv]
Version=0.5.0-61

[R]
Version=3.6.0
Repositories=
	CRAN=https://cran.rstudio.com/

[R/Package/BH]
Package=BH
Version=1.66.0-1
Source=CRAN
Hash=ce6febf0e10393b4d79a1f3b51be4b39

[R/Package/DBI]
Package=DBI
Version=1.0.0
Source=CRAN
Hash=2b2b6ea2111e1e57e192765d5013a3c5

[R/Package/ISOweek]
Package=ISOweek
Version=0.6-2
Source=CRAN
Hash=7c7dbe4bc3500ae8c09e84066e3121d8

[R/Package/R.methodsS3]
Package=R.methodsS3
Version=1.7.1
Source=CRAN
Hash=d2c60692c1500e87b06a602b316817ba

[R/Package/R.oo]
Package=R.oo
Version=1.22.0
Source=CRAN
Hash=3ed00bcfb667ecbfcc1ddfa07d63e6b3

[R/Package/R.utils]
Package=R.utils
Version=2.6.0
Source=CRAN
Hash=f4fb1287dc686b742a74d4241e46cebe

[R/Package/R6]
Package=R6
Version=2.3.0
Source=CRAN
Hash=79403ef5bde27ea131f728d81a2899bc

[R/Package/RColorBrewer]
Package=RColorBrewer
Version=1.1-2
Source=CRAN
Hash=f8a3bcc800d613797f1dfdf8ef4f0bfc

[R/Package/RCurl]
Package=RCurl
Version=1.95-4.11
Source=CRAN
Hash=f279c8e108e9b503a297987a4d171c93

[R/Package/RJDBC]
Package=RJDBC
Version=0.2-7.1
Source=CRAN
Hash=0db4e5c3e805de46be520b5e0a8c3634

[R/Package/RMySQL]
Package=RMySQL
Version=0.10.15
Source=CRAN
Hash=6bd4d80740288dc12a2daaaa27bfeb1b

[R/Package/RPostgreSQL]
Package=RPostgreSQL
Version=0.6-2
Source=CRAN
Hash=8c97787c6afc7ba0062547a0f7777592

[R/Package/RSQLite]
Package=RSQLite
Version=2.1.1
Source=CRAN
Hash=1551291db703e1e2e612a53d6ea88803

[R/Package/Rcpp]
Package=Rcpp
Version=1.0.1
Source=CRAN
Hash=94bf4b635dd6abac1765cff90ba98235

[R/Package/assertthat]
Package=assertthat
Version=0.2.0
Source=CRAN
Hash=f9e23f874114d5a22471d3e26346a0c1

[R/Package/aws.s3]
Package=aws.s3
Version=0.3.11
Source=CRAN
Hash=3379c6b6a23bc7163bffd55070d54cef

[R/Package/aws.signature]
Package=aws.signature
Version=0.4.4
Source=CRAN
Hash=d41244520c8ea3fd8dcc0033e3a19232

[R/Package/backports]
Package=backports
Version=1.1.2
Source=CRAN
Hash=ecc976fb967b74718ab77da4e69c8133

[R/Package/base64enc]
Package=base64enc
Version=0.1-3
Source=CRAN
Hash=d355963b4b1c3039bfe8d65611a11cca

[R/Package/bigrquery]
Package=bigrquery
Version=1.0.0
Source=CRAN
Hash=4d5d28d3ce79f2ac46bcb082d8d0a0ba

[R/Package/bindr]
Package=bindr
Version=0.1.1
Source=CRAN
Hash=955970d2b0a64d115306b01938bc097a

[R/Package/bindrcpp]
Package=bindrcpp
Version=0.2.2
Source=CRAN
Hash=b894708bedd7f0a33a39853b155a952e

[R/Package/bit]
Package=bit
Version=1.1-14
Source=CRAN
Hash=915a13dd2f8633d92971640ed1498e5b

[R/Package/bit64]
Package=bit64
Version=0.9-7
Source=CRAN
Hash=805d4ae996fa46f4f8436500959d669b

[R/Package/bitops]
Package=bitops
Version=1.0-6
Source=CRAN
Hash=62408262624d9f8e436f51ca901424e2

[R/Package/blob]
Package=blob
Version=1.1.1
Source=CRAN
Hash=9d60568146fc9c3351d8b2f8db53e677

[R/Package/brew]
Package=brew
Version=1.0-6
Source=CRAN
Hash=190fd31e9253446523a8ee4642229516

[R/Package/callr]
Package=callr
Version=3.2.0
Source=CRAN
Hash=f1e3e635828bc08b88fc70a722800df5

[R/Package/cellranger]
Package=cellranger
Version=1.1.0
Source=CRAN
Hash=2cd2a065192f3ba08a919d8800dba7e0

[R/Package/cli]
Package=cli
Version=1.1.0
Source=CRAN
Hash=9b3dc7798f53ba3050b41ce4a3febdc5

[R/Package/clipr]
Package=clipr
Version=0.6.0
Source=CRAN
Hash=1b4c6b49dca948d2f95a741ae8f52edd

[R/Package/clisymbols]
Package=clisymbols
Version=1.2.0
Source=CRAN
Hash=ce91c46caba29e30c44cfd87659bf8a4

[R/Package/colorspace]
Package=colorspace
Version=1.3-2
Source=CRAN
Hash=92ece9c0e6e9e3479a8df645e136b35b

[R/Package/commonmark]
Package=commonmark
Version=1.5
Source=CRAN
Hash=aa8d6e5e9378e8f6d2d2fee512590e52

[R/Package/crayon]
Package=crayon
Version=1.3.4
Source=CRAN
Hash=d308ead32010b8e4d76c4690427da50b

[R/Package/curl]
Package=curl
Version=3.2
Source=CRAN
Hash=704443d5df2ad0c381f0a6ec1221e444

[R/Package/desc]
Package=desc
Version=1.2.0
Source=CRAN
Hash=0119aa659b9c1db195b4bd7c617d18c0

[R/Package/devtools]
Package=devtools
Version=2.0.2
Source=CRAN
Hash=7c464263bfa1c55ebada53c6d851812f

[R/Package/digest]
Package=digest
Version=0.6.18
Source=CRAN
Hash=53c009a1091c660e026276dd64379116

[R/Package/dplyr]
Package=dplyr
Version=0.7.8
Source=CRAN
Hash=3cc520cbd00dc3e2a44c00f86b5d55c9

[R/Package/evaluate]
Package=evaluate
Version=0.10.1
Source=CRAN
Hash=089df207fbf24f247e4f14fd5b791dad

[R/Package/fs]
Package=fs
Version=1.3.1
Source=CRAN
Hash=dba7e43c4103d978cb7c95b97987cc68

[R/Package/gh]
Package=gh
Version=1.0.1
Source=CRAN
Hash=3fc5d4d6893bd1598318a35def5e9d23

[R/Package/git2r]
Package=git2r
Version=0.25.2
Source=CRAN
Hash=1abf4306c489a2f233fd559ed5cdea21

[R/Package/glue]
Package=glue
Version=1.3.0
Source=CRAN
Hash=e531db28af47f460fa43ba964a4f051e

[R/Package/gtable]
Package=gtable
Version=0.2.0
Source=CRAN
Hash=ae2c6bf80adc48cd67f6e09860c5451d

[R/Package/highr]
Package=highr
Version=0.6
Source=CRAN
Hash=afd743a967844e6dadda638156f76459

[R/Package/hms]
Package=hms
Version=0.4.2
Source=CRAN
Hash=027298fb177899be8299a815a8d5495d

[R/Package/httr]
Package=httr
Version=1.3.1.9000
Source=unknown
Hash=b7665c345a3fa244a02086691d52cac5

[R/Package/ini]
Package=ini
Version=0.3.1
Source=CRAN
Hash=4a15d8cfc931554fb2e71d66c1313b45

[R/Package/jsonlite]
Package=jsonlite
Version=1.5
Source=CRAN
Hash=3117203bf33ca6948729f027f7e59181

[R/Package/knitr]
Package=knitr
Version=1.20
Source=CRAN
Hash=3a4f618c2e0e8696955b4becb413a683

[R/Package/labeling]
Package=labeling
Version=0.3
Source=CRAN
Hash=e1f613894f080d1eee41c34b281a2184

[R/Package/lazyeval]
Package=lazyeval
Version=0.2.1
Source=CRAN
Hash=560e58a057dc5cb1270ce6da30edeb88

[R/Package/lubridate]
Package=lubridate
Version=1.7.4
Source=CRAN
Hash=d55fdb3732a8f047e49b86064dd78984

[R/Package/magrittr]
Package=magrittr
Version=1.5
Source=CRAN
Hash=dee1d97cffddfd3ed969e224bd0826d0

[R/Package/mailR]
Package=mailR
Version=0.4.1
Source=CRAN
Hash=cbf42f6386c0b342eb362e129214e18a

[R/Package/markdown]
Package=markdown
Version=0.8
Source=CRAN
Hash=fdcd69903c0aeba14945e77d88c8c852

[R/Package/memoise]
Package=memoise
Version=1.1.0
Source=CRAN
Hash=22ca9b285c10f5dd8c4d1e90231ce558

[R/Package/mime]
Package=mime
Version=0.6
Source=CRAN
Hash=80ae456badc246e62ce407667129a9fb

[R/Package/munsell]
Package=munsell
Version=0.5.0
Source=CRAN
Hash=9111af6c6dec65538ebd3de6c0bae864

[R/Package/openssl]
Package=openssl
Version=1.1
Source=CRAN
Hash=c8d50bc6f3d304ba85e7049e519e0103

[R/Package/packrat]
Package=packrat
Version=0.5.0
Source=CRAN
Hash=aa1fbebb6ca276f933b9f77da6d02ef3

[R/Package/pillar]
Package=pillar
Version=1.2.2
Source=CRAN
Hash=32761c65152edf73dfd3b689a51ef9a4

[R/Package/pkgbuild]
Package=pkgbuild
Version=1.0.2
Source=CRAN
Hash=21d94288d19b012009948f5b95bd5412

[R/Package/pkgconfig]
Package=pkgconfig
Version=2.0.2
Source=CRAN
Hash=2dd2d8867e4f0173ea2ce029d630a086

[R/Package/pkgload]
Package=pkgload
Version=1.0.2
Source=CRAN
Hash=f214a72af3442fdd3396ceccbb7d7f44

[R/Package/plogr]
Package=plogr
Version=0.2.0
Source=CRAN
Hash=1a8304cc1382ef64e3b710ba589d7bc0

[R/Package/plyr]
Package=plyr
Version=1.8.4
Source=CRAN
Hash=37dd0f3aadee2ac99e47168f4bffddb7

[R/Package/praise]
Package=praise
Version=1.0.0
Source=CRAN
Hash=3940f2f321d5fa9fb72b8887b0454660

[R/Package/prettyunits]
Package=prettyunits
Version=1.0.2
Source=CRAN
Hash=33ce93b23647e85c127f8e1bb08604fc

[R/Package/processx]
Package=processx
Version=3.3.1
Source=CRAN
Hash=6cb4a4d0e13190ea58a2ed9e39adf967

[R/Package/progress]
Package=progress
Version=1.2.0
Source=CRAN
Hash=f462b2404c3bc6d876fb47f74bb8c0e2

[R/Package/ps]
Package=ps
Version=1.2.1
Source=CRAN
Hash=cfabc4bae5568338fc449b0747d2b04a

[R/Package/purrr]
Package=purrr
Version=0.2.5
Source=CRAN
Hash=be15335529da7a4ed46e4664f6e7353f

[R/Package/rJava]
Package=rJava
Version=0.9-10
Source=CRAN
Hash=6d6de4b82f99563b69703e13a1a3dac8

[R/Package/rapidjsonr]
Package=rapidjsonr
Version=1.0.0
Source=CRAN
Hash=8f17c2e4ac783c96908473c816812b54

[R/Package/rcmdcheck]
Package=rcmdcheck
Version=1.3.3
Source=CRAN
Hash=577b91be8aea851ea27aad3585adef05

[R/Package/readxl]
Package=readxl
Version=1.1.0
Source=CRAN
Hash=01067981c615cb8ff027f268c3cd03a6

[R/Package/rematch]
Package=rematch
Version=1.0.1
Source=CRAN
Hash=d3d55a556f7f2e74f449d6a53b8abf8e

[R/Package/remotes]
Package=remotes
Version=2.0.4
Source=CRAN
Hash=2356800bf0714f0daefddc6889508739

[R/Package/reshape2]
Package=reshape2
Version=1.4.3
Source=CRAN
Hash=ac685130d1a25e3f6470960fd29c5693

[R/Package/rlang]
Package=rlang
Version=0.3.0.1
Source=CRAN
Hash=acf2fdb1d8b0826ee2a17b425208db93

[R/Package/roxygen2]
Package=roxygen2
Version=6.0.1
Source=CRAN
Hash=0cd7a1f0e0bc7282d53104d693945542

[R/Package/rprojroot]
Package=rprojroot
Version=1.3-2
Source=CRAN
Hash=5382761b8b318da6dd3fb0f6dae3c43a

[R/Package/rstudioapi]
Package=rstudioapi
Version=0.7
Source=CRAN
Hash=ff4efa95a406ed6dcfa290ae46083b73

[R/Package/scales]
Package=scales
Version=1.0.0
Source=CRAN
Hash=a96e9571cd875b7b934990d85b7a3c18

[R/Package/sessioninfo]
Package=sessioninfo
Version=1.1.1
Source=CRAN
Hash=017efbc7877606b886a2fb3d01c0bbda

[R/Package/stringi]
Package=stringi
Version=1.2.4
Source=CRAN
Hash=9ed7a7c9ec0a65a1dfa792066758b384

[R/Package/stringr]
Package=stringr
Version=1.3.1
Source=CRAN
Hash=f1117ab180fb4d9af1e60a604c91c6be

[R/Package/testthat]
Package=testthat
Version=2.0.1
Source=CRAN
Hash=fb36d69d096ddaf4fddc078dda46898d

[R/Package/tibble]
Package=tibble
Version=1.4.2
Source=CRAN
Hash=de2fe6835edd92efe743d47eafff99f2

[R/Package/tidyselect]
Package=tidyselect
Version=0.2.5
Source=CRAN
Hash=dc3fcbc21f04b293e0794e24982cf357

[R/Package/usethis]
Package=usethis
Version=1.5.0
Source=CRAN
Hash=fb5acd04604da18ce5bc4db926d4037d

[R/Package/utf8]
Package=utf8
Version=1.1.3
Source=CRAN
Hash=19f6b73e1fdff4400168be0d0c8f43f0

[R/Package/viridisLite]
Package=viridisLite
Version=0.3.0
Source=CRAN
Hash=1f264fa42320c4f44b1689d89101e823

[R/Package/whisker]
Package=whisker
Version=0.3-2
Source=CRAN
Hash=c6d8a035a88c6e3222f0efaac18406f6

[R/Package/withr]
Package=withr
Version=2.1.2
Source=CRAN
Hash=7c9aef08038f47e6c1532ed574a0e087

[R/Package/writexl]
Package=writexl
Version=0.2
Source=CRAN
Hash=0266f5944a7c54bb71a9291db3a5397a

[R/Package/xml2]
Package=xml2
Version=1.2.0.9000
Source=GitHub
RemoteType=github
RemoteHost=api.github.com
RemoteRepo=xml2
RemoteUsername=r-lib
RemoteRef=master
RemoteSha=39fb4f4ab6f6064a50533d2e1ee64158972dd923
Hash=47ab8f6e5db73f7b1df04d7b3d15ad50

[R/Package/xopen]
Package=xopen
Version=1.0.0
Source=CRAN
Hash=ec32d86b4bcfa2cfa648dc0e1e46e24d

[R/Package/yaml]
Package=yaml
Version=2.2.0
Source=CRAN
Hash=3a313c96061c4ac790de611dc57ebd1f

**Comment by kevinushey** [comment]
I think I know what's going on now. Are you using a Homebrew version of R, or perhaps R compiled from source through some other means?

If one requests binary packages with Homebrew R, the list of source packages is returned instead. For example:

```
> ap <- available.packages(type = "source")
> ap["ggplot2", c("Package", "Version", "Repository")]
                               Package                                Version
                             "ggplot2"                                "3.2.0"
                            Repository
"https://cran.rstudio.com/src/contrib"
```

This is because in Homebrew R installations, `.Platform$pkgType` reports "source" rather than "binary", and `renv` fails to detect this case.

I'll see if I can get this fixed up.

**Comment by kevinushey** [comment]
I think this should be fixed up now. Can you try executing `renv::upgrade()` in your project and see if the issue still reproduces?

**Comment by hugeme** [comment]
@kevinushey yes you are right, I was using homebrew. And yes, that issue was solved with your fix. Thank you for that nice experience!

**Comment by Athanasiamo** [comment]
just here to say that I had a similar issue just now, and `renv::upgrade()` did the trick.

**Comment by egouldo** [comment]
Is there another solution apart from upgrading? I am running `renv::` version 1.0.3 and having this same problem. I've tried deleting the packages from my project library, and then disabling the cache to reinstall but am still getting the same problem!

**Comment by kevinushey** [comment]
> Is there another solution apart from upgrading? I am running renv:: version 1.0.3 and having this same problem.

This issue should've been resolved some time ago. Can you please provide the full output log, including the command you're executing and the output you're seeing?
